import { Personality, WrappedData, WrappedSettings } from "./types";

function esc(s: string): string {
	return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function formatNumber(n: number): string {
	return n.toLocaleString("en-US");
}

function heroNum(n: number, suffix = ""): string {
	return `<div class="ow-hero-num">${formatNumber(n)}${suffix}</div>`;
}

export interface WrappedCard {
	id: string;
	title: string;
	html: string;
}

const ACCENTS: Record<string, string> = {
	journal: "#f59e0b",
	tasks: "#22d3ee",
	zettelkasten: "#a78bfa",
	collector: "#fb7185",
	balanced: "#34d399",
};

export function buildCards(data: WrappedData, personality: Personality, settings: WrappedSettings): WrappedCard[] {
	const accent = ACCENTS[personality.archetype] ?? ACCENTS.balanced;
	const year = data.year;

	const cover: WrappedCard = {
		id: "cover",
		title: `wrapped-${year}-cover`,
		html: `
		<div class="ow-card ow-cover">
			<div class="ow-cover-top">
				<span class="ow-vault-name">${esc(data.vaultName)}</span>
				<span class="ow-year">${year}</span>
			</div>
<div class="ow-cover-mid">
			<div class="ow-personality-emoji">${personality.emoji}</div>
			<div class="ow-wrapped-title">${year} Wrapped</div>
			<div class="ow-personality-badge" style="--accent:${accent}">${esc(personality.label)}</div>
			<div class="ow-subtitle">${year} Wrapped</div>
		</div>
			<div class="ow-cover-footer">Generated by Obsidian Wrapped · your vault, your story</div>
		</div>`,
	};

	const heroStats: WrappedCard = {
		id: "stats",
		title: `wrapped-${year}-stats`,
		html: `
		<div class="ow-card">
			<div class="ow-card-title" style="--accent:${accent}">YOUR YEAR IN NUMBERS</div>
			<div class="ow-hero-grid">
				<div class="ow-hero">${heroNum(data.totalNotesCreatedYear)}<div class="ow-hero-label">notes created</div></div>
				<div class="ow-hero">${heroNum(data.totalWordsYear)}<div class="ow-hero-label">words written</div></div>
				<div class="ow-hero">${heroNum(data.wordsPerNoteYear)}<div class="ow-hero-label">words per note</div></div>
				<div class="ow-hero">${heroNum(data.perDay)}<div class="ow-hero-label">notes per day</div></div>
			</div>
			<div class="ow-note">All-time vault: ${formatNumber(data.totalNotesAllTime)} notes · ${formatNumber(data.totalWordsAll)} words</div>
		</div>`,
	};

	const monthly: WrappedCard = {
		id: "monthly",
		title: `wrapped-${year}-monthly`,
		html: `
		<div class="ow-card">
			<div class="ow-card-title" style="--accent:${accent}">YOUR YEAR, MONTH BY MONTH</div>
			<div class="ow-bars">
				${monthlyBars(data, accent)}
			</div>
			<div class="ow-bars-foot">You were busiest in ${esc(data.mostActiveMonthName)} — mostly on ${data.mostActiveDayOfWeek}s.</div>
		</div>`,
	};

	const rhythm: WrappedCard = {
		id: "rhythm",
		title: `wrapped-${year}-rhythm`,
		html: `
		<div class="ow-card">
			<div class="ow-card-title" style="--accent:${accent}">YOUR WRITING RHYTHM</div>
			<div class="ow-rhythm-grid">
				<div class="ow-rythm-cell"><div class="ow-rhythm-num">🔥 ${data.writingStreak}</div><div class="ow-rhythm-label">current writing streak (days)</div></div>
				<div class="ow-rythm-cell"><div class="ow-rhythm-num">🌙 ${data.midnightWrites}</div><div class="ow-rhythm-label">edits past midnight</div></div>
				<div class="ow-rythm-cell"><div class="ow-rhythm-num">💤 ${data.longestBreak}</div><div class="ow-rhythm-label">longest break (days)</div></div>
				<div class="ow-rythm-cell"><div class="ow-rhythm-num">🔁 ${data.revivedNotes}</div><div class="ow-rhythm-label">old notes you revived</div></div>
			</div>
		</div>`,
	};

	const ideas: WrappedCard = {
		id: "ideas",
		title: `wrapped-${year}-influential`,
		html: `
		<div class="ow-card">
			<div class="ow-card-title" style="--accent:${accent}">YOUR MOST INFLUENTIAL IDEAS</div>
			<div class="ow-list">
				${noteList(data.mostInfluential, "linked", "inbound links")}
			</div>
		</div>`,
	};

	const archetypeCards: WrappedCard[] = [];
	if (personality.archetype === "journal") {
		archetypeCards.push({
			id: "journal",
			title: `wrapped-${year}-journal`,
			html: `
			<div class="ow-card">
				<div class="ow-card-title" style="--accent:${accent}">YOUR JOURNAL</div>
				<div class="ow-hero-grid">
					<div class="ow-hero">${heroNum(data.journalEntriesYear)}<div class="ow-hero-label">journal entries</div></div>
					<div class="ow-hero">${heroNum(data.journalWordsYear)}<div class="ow-hero-label">journal words</div></div>
					<div class="ow-hero">${heroNum(data.dailyNoteStreak)}<div class="ow-hero-label">longest daily streak</div></div>
					<div class="ow-hero">${heroNum(data.midnightWrites)}<div class="ow-hero-label">pages after midnight</div></div>
				</div>
			</div>`,
		});
	}
	if (personality.archetype === "tasks") {
		archetypeCards.push({
			id: "tasks",
			title: `wrapped-${year}-tasks`,
			html: `
			<div class="ow-card">
				<div class="ow-card-title" style="--accent:${accent}">YOUR TASKS</div>
				<div class="ow-hero-grid">
					<div class="ow-hero">${heroNum(data.tasksCreated)}<div class="ow-hero-label">tasks created</div></div>
					<div class="ow-hero">${heroNum(data.tasksCompleted)}<div class="ow-hero-label">tasks completed</div></div>
					<div class="ow-hero">${heroNum(data.taskCompletionRate, "%")}<div class="ow-hero-label">completion rate</div></div>
					<div class="ow-hero">${heroNum(data.tasksAbandoned)}<div class="ow-hero-label">still waiting</div></div>
				</div>
			</div>`,
		});
	}
	if (personality.archetype === "zettelkasten") {
		archetypeCards.push({
			id: "zettel",
			title: `wrapped-${year}-zettelkasten`,
			html: `
			<div class="ow-card">
				<div class="ow-card-title" style="--accent:${accent}">YOUR WEB OF IDEAS</div>
				<div class="ow-rhythm-grid">
					<div class="ow-rythm-cell"><div class="ow-rhythm-num">${data.linkDensity}</div><div class="ow-rhythm-label">links per note</div></div>
					<div class="ow-rythm-cell"><div class="ow-rhythm-num">${data.notesWithLinksPct}%</div><div class="ow-rhythm-label">notes with links</div></div>
					<div class="ow-rythm-cell"><div class="ow-rhythm-num">${data.orphanStats.pct}%</div><div class="ow-rhythm-label">orphan notes</div></div>
				</div>
				<div class="ow-list-label">Your hubs (most outgoing links)</div>
				<div class="ow-list">${noteList(data.hubNotes, "hub", "links out")}</div>
			</div>`,
		});
	}
	if (personality.archetype === "collector") {
		archetypeCards.push({
			id: "collector",
			title: `wrapped-${year}-collector`,
			html: `
			<div class="ow-card">
				<div class="ow-card-title" style="--accent:${accent}">YOUR COLLECTION</div>
				<div class="ow-hero-grid">
					<div class="ow-hero">${heroNum(data.totalNotesCreatedYear)}<div class="ow-hero-label">notes gathered</div></div>
					<div class="ow-hero">${heroNum(data.orphanStats.pct, "%")}<div class="ow-hero-label">orphans</div></div>
					<div class="ow-hero">${heroNum(data.wordsPerNoteYear)}<div class="ow-hero-label">words per note</div></div>
				</div>
				<div class="ow-note">Quantity is its own kind of knowledge.</div>
			</div>`,
		});
	}

	const embarrassing: WrappedCard = {
		id: "oops",
		title: `wrapped-${year}-oops`,
		html: `
		<div class="ow-card ow-oops">
			<div class="ow-card-title" style="--accent:#fb7185">THE EMBARRASSING STAT</div>
			<div class="ow-oops-text">${esc(data.embarrassing)}</div>
		</div>`,
	};

	const facts: WrappedCard = {
		id: "facts",
		title: `wrapped-${year}-facts`,
		html: `
		<div class="ow-card">
			<div class="ow-card-title" style="--accent:${accent}">FUN FACTS</div>
			<div class="ow-fact"><span class="ow-fact-emoji">🏆</span><span>Longest note: <b>${esc(data.longestNote.basename)}</b> (${formatNumber(data.longestWordCount)} words)</span></div>
			<div class="ow-fact"><span class="ow-fact-emoji">🌱</span><span>First note: ${data.firstNote ? esc(data.firstNote.path) : "—"}</span></div>
			<div class="ow-fact"><span class="ow-fact-emoji">🍃</span><span>Lightest note: <b>${esc(data.weirdestPath)}</b> — ${data.weirdestNote}</span></div>
			<div class="ow-fact"><span class="ow-fact-emoji">🗓️</span><span>Your vault has existed for ${data.existedDays} days</span></div>
		</div>`,
	};

	return [cover, heroStats, monthly, rhythm, ideas, ...archetypeCards, embarrassing, facts];
}

function monthlyBars(data: WrappedData, accent: string): string {
	const max = Math.max(1, ...data.monthlyCreated.map((b) => b.count));
	const months = fillMonths(data);
	return months
		.map((b) => {
			const pct = b.count ? Math.max(4, Math.round((b.count / max) * 100)) : 0;
			return `
			<div class="ow-bar-row">
				<span class="ow-bar-label">${b.label}</span>
				<div class="ow-bar-track"><div class="ow-bar-fill" style="width:${pct}%;--accent:${accent}"></div></div>
				<span class="ow-bar-count">${formatNumber(b.count)}</span>
			</div>`;
		})
		.join("");
}

function fillMonths(data: WrappedData) {
	const byMonth = new Map(data.monthlyCreated.map((b) => [b.month, b]));
	const out: { month: string; label: string; count: number }[] = [];
	for (let m = 0; m < 12; m++) {
		const key = `${data.year}-${String(m + 1).padStart(2, "0")}`;
		const found = byMonth.get(key);
		out.push({
			month: key,
			label: found?.label ?? new Date(data.year, m, 1).toLocaleString("en", { month: "short" }),
			count: found?.count ?? 0,
		});
	}
	return out;
}

function noteList(list: { basename: string; value: number }[], idc: string, suffix: string): string {
	if (list.length === 0) {
		return `<div class="ow-empty">No linked notes yet — the web is still being spun.</div>`;
	}
	return list
		.map((n, i) => {
			const num = ["🥇", "🥈", "🥉"][i] ?? `${i + 1}`;
			return `
			<div class="ow-note-row">
				<span class="ow-rank">${num}</span>
				<span class="ow-note-name">${esc(n.basename)}</span>
				<span class="ow-note-count">${formatNumber(n.value)} ${suffix}</span>
			</div>`;
		})
		.join("");
}