import { Personality, TopNote, WrappedData, WrappedSettings } from "./types";

function formatNumber(n: number): string {
	return n.toLocaleString("en-US");
}

function setAccent(el: HTMLElement, accent: string): HTMLElement {
	el.style.setProperty("--accent", accent);
	return el;
}

function heroNum(n: number, suffix = ""): HTMLDivElement {
	return createDiv({ cls: "ow-hero-num", text: formatNumber(n) + suffix });
}

export interface WrappedCard {
	id: string;
	title: string;
	element: HTMLElement;
}

const ACCENTS: Record<string, string> = {
	journal: "#f59e0b",
	tasks: "#22d3ee",
	zettelkasten: "#a78bfa",
	collector: "#fb7185",
	balanced: "#34d399",
};

export function buildCards(data: WrappedData, personality: Personality, settings: WrappedSettings): WrappedCard[] {
	const accent = ACCENTS[personality.archetype] ?? ACCENTS.balanced;
	const year = data.year;
	const cards: WrappedCard[] = [];

	// ── Cover ──
	{
		const card = createDiv({ cls: "ow-card ow-cover" });
		const top = createDiv({ cls: "ow-cover-top" });
		top.appendChild(createSpan({ cls: "ow-vault-name", text: data.vaultName }));
		top.appendChild(createSpan({ cls: "ow-year", text: String(year) }));
		card.appendChild(top);

		const mid = createDiv({ cls: "ow-cover-mid" });
		mid.appendChild(createDiv({ cls: "ow-personality-emoji", text: personality.emoji }));
		mid.appendChild(createDiv({ cls: "ow-wrapped-title", text: `${year} Wrapped` }));
		const badge = createDiv({ cls: "ow-personality-badge", text: personality.label });
		setAccent(badge, accent);
		mid.appendChild(badge);
		mid.appendChild(createDiv({ cls: "ow-subtitle", text: `${year} Wrapped` }));
		card.appendChild(mid);

		card.appendChild(createDiv({ cls: "ow-cover-footer", text: "Generated by Wrapped · your vault, your story" }));
		cards.push({ id: "cover", title: `wrapped-${year}-cover`, element: card });
	}

	// ── Hero stats ──
	{
		const card = createDiv({ cls: "ow-card" });
		const titleEl = createDiv({ cls: "ow-card-title", text: "YOUR YEAR IN NUMBERS" });
		setAccent(titleEl, accent);
		card.appendChild(titleEl);

		const grid = createDiv({ cls: "ow-hero-grid" });
		const items: [number, string][] = [
			[data.totalNotesCreatedYear, "notes created"],
			[data.totalWordsYear, "words written"],
			[data.wordsPerNoteYear, "words per note"],
			[data.perDay, "notes per day"],
		];
		for (const [num, label] of items) {
			const cell = createDiv({ cls: "ow-hero" });
			cell.appendChild(heroNum(num));
			cell.appendChild(createDiv({ cls: "ow-hero-label", text: label }));
			grid.appendChild(cell);
		}
		card.appendChild(grid);
		card.appendChild(createDiv({ cls: "ow-note", text: `All-time vault: ${formatNumber(data.totalNotesAllTime)} notes · ${formatNumber(data.totalWordsAll)} words` }));
		cards.push({ id: "stats", title: `wrapped-${year}-stats`, element: card });
	}

	// ── Monthly bars ──
	{
		const card = createDiv({ cls: "ow-card" });
		const titleEl = createDiv({ cls: "ow-card-title", text: "YOUR YEAR, MONTH BY MONTH" });
		setAccent(titleEl, accent);
		card.appendChild(titleEl);

		const bars = monthlyBars(data, accent);
		card.appendChild(bars);
		card.appendChild(createDiv({ cls: "ow-bars-foot", text: `You were busiest in ${data.mostActiveMonthName} — mostly on ${data.mostActiveDayOfWeek}s.` }));
		cards.push({ id: "monthly", title: `wrapped-${year}-monthly`, element: card });
	}

	// ── Writing rhythm ──
	{
		const card = createDiv({ cls: "ow-card" });
		const titleEl = createDiv({ cls: "ow-card-title", text: "YOUR WRITING RHYTHM" });
		setAccent(titleEl, accent);
		card.appendChild(titleEl);

		const grid = createDiv({ cls: "ow-rhythm-grid" });
		const cells: [string, string][] = [
			[`🔥 ${data.writingStreak}`, "current writing streak (days)"],
			[`🌙 ${data.midnightWrites}`, "edits past midnight"],
			[`💤 ${data.longestBreak}`, "longest break (days)"],
			[`🔁 ${data.revivedNotes}`, "old notes you revived"],
		];
		for (const [num, label] of cells) {
			const cell = createDiv({ cls: "ow-rythm-cell" });
			cell.appendChild(createDiv({ cls: "ow-rhythm-num", text: num }));
			cell.appendChild(createDiv({ cls: "ow-rhythm-label", text: label }));
			grid.appendChild(cell);
		}
		card.appendChild(grid);
		cards.push({ id: "rhythm", title: `wrapped-${year}-rhythm`, element: card });
	}

	// ── Most influential ideas ──
	{
		const card = createDiv({ cls: "ow-card" });
		const titleEl = createDiv({ cls: "ow-card-title", text: "YOUR MOST INFLUENTIAL IDEAS" });
		setAccent(titleEl, accent);
		card.appendChild(titleEl);
		card.appendChild(noteList(data.mostInfluential, "inbound links"));
		cards.push({ id: "ideas", title: `wrapped-${year}-influential`, element: card });
	}

	// ── Archetype cards ──
	if (personality.archetype === "journal") {
		cards.push(archetypeJournal(data, accent, year));
	}
	if (personality.archetype === "tasks") {
		cards.push(archetypeTasks(data, accent, year));
	}
	if (personality.archetype === "zettelkasten") {
		cards.push(archetypeZettel(data, accent, year));
	}
	if (personality.archetype === "collector") {
		cards.push(archetypeCollector(data, accent, year));
	}

	// ── Embarrassing stat ──
	{
		const card = createDiv({ cls: "ow-card ow-oops" });
		const titleEl = createDiv({ cls: "ow-card-title", text: "THE EMBARRASSING STAT" });
		setAccent(titleEl, "#fb7185");
		card.appendChild(titleEl);
		card.appendChild(createDiv({ cls: "ow-oops-text", text: data.embarrassing }));
		cards.push({ id: "oops", title: `wrapped-${year}-oops`, element: card });
	}

	// ── Fun facts ──
	{
		const card = createDiv({ cls: "ow-card" });
		const titleEl = createDiv({ cls: "ow-card-title", text: "FUN FACTS" });
		setAccent(titleEl, accent);
		card.appendChild(titleEl);

		const facts = [
			{ emoji: "🏆", parts: ["Longest note: ", { bold: data.longestNote.basename }, ` (${formatNumber(data.longestWordCount)} words)`] },
			{ emoji: "🌱", parts: ["First note: ", { text: data.firstNote ? data.firstNote.path : "—" }] },
			{ emoji: "🍃", parts: ["Lightest note: ", { bold: data.weirdestPath }, ` — ${data.weirdestNote}`] },
			{ emoji: "🗓️", parts: [`Your vault has existed for ${data.existedDays} days`] },
		];

		for (const f of facts) {
			const row = createDiv({ cls: "ow-fact" });
			row.appendChild(createSpan({ cls: "ow-fact-emoji", text: f.emoji }));
			const span = createSpan();
			for (const p of f.parts) {
				if (typeof p === "string") {
					span.appendText(p);
				} else if ("bold" in p) {
					span.appendChild(createEl("b", { text: p.bold }));
				} else {
					span.appendText(p.text);
				}
			}
			row.appendChild(span);
			card.appendChild(row);
		}

		cards.push({ id: "facts", title: `wrapped-${year}-facts`, element: card });
	}

	return cards;
}

function monthlyBars(data: WrappedData, accent: string): HTMLElement {
	const max = Math.max(1, ...data.monthlyCreated.map((b) => b.count));
	const months = fillMonths(data);
	const container = createDiv({ cls: "ow-bars" });

	for (const b of months) {
		const pct = b.count ? Math.max(4, Math.round((b.count / max) * 100)) : 0;
		const row = createDiv({ cls: "ow-bar-row" });
		row.appendChild(createSpan({ cls: "ow-bar-label", text: b.label }));

		const track = createDiv({ cls: "ow-bar-track" });
		const fill = createDiv({ cls: "ow-bar-fill" });
		fill.style.width = `${pct}%`;
		setAccent(fill, accent);
		track.appendChild(fill);
		row.appendChild(track);

		row.appendChild(createSpan({ cls: "ow-bar-count", text: formatNumber(b.count) }));
		container.appendChild(row);
	}

	return container;
}

function fillMonths(data: WrappedData) {
	const byMonth = new Map(data.monthlyCreated.map((b) => [b.month, b]));
	const out: { month: string; label: string; count: number }[] = [];
	for (let m = 0; m < 12; m++) {
		const key = `${data.year}-${String(m + 1).padStart(2, "0")}`;
		const found = byMonth.get(key);
		out.push({
			month: key,
			label: found?.label ?? new Date(data.year, m, 1).toLocaleString("en", { month: "short" }),
			count: found?.count ?? 0,
		});
	}
	return out;
}

function noteList(list: { basename: string; value: number }[], suffix: string): HTMLElement {
	const container = createDiv({ cls: "ow-list" });

	if (list.length === 0) {
		container.appendChild(createDiv({ cls: "ow-empty", text: "No linked notes yet — the web is still being spun." }));
		return container;
	}

	for (let i = 0; i < list.length; i++) {
		const n = list[i];
		const num = ["🥇", "🥈", "🥉"][i] ?? `${i + 1}`;
		const row = createDiv({ cls: "ow-note-row" });
		row.appendChild(createSpan({ cls: "ow-rank", text: num }));
		row.appendChild(createSpan({ cls: "ow-note-name", text: n.basename }));
		row.appendChild(createSpan({ cls: "ow-note-count", text: `${formatNumber(n.value)} ${suffix}` }));
		container.appendChild(row);
	}

	return container;
}

function archetypeJournal(data: WrappedData, accent: string, year: number): WrappedCard {
	const card = createDiv({ cls: "ow-card" });
	const titleEl = createDiv({ cls: "ow-card-title", text: "YOUR JOURNAL" });
	setAccent(titleEl, accent);
	card.appendChild(titleEl);

	const grid = createDiv({ cls: "ow-hero-grid" });
	const items: [number, string][] = [
		[data.journalEntriesYear, "journal entries"],
		[data.journalWordsYear, "journal words"],
		[data.dailyNoteStreak, "longest daily streak"],
		[data.midnightWrites, "pages after midnight"],
	];
	for (const [num, label] of items) {
		const cell = createDiv({ cls: "ow-hero" });
		cell.appendChild(heroNum(num));
		cell.appendChild(createDiv({ cls: "ow-hero-label", text: label }));
		grid.appendChild(cell);
	}
	card.appendChild(grid);
	return { id: "journal", title: `wrapped-${year}-journal`, element: card };
}

function archetypeTasks(data: WrappedData, accent: string, year: number): WrappedCard {
	const card = createDiv({ cls: "ow-card" });
	const titleEl = createDiv({ cls: "ow-card-title", text: "YOUR TASKS" });
	setAccent(titleEl, accent);
	card.appendChild(titleEl);

	const grid = createDiv({ cls: "ow-hero-grid" });
	const items: [number, string][] = [
		[data.tasksCreated, "tasks created"],
		[data.tasksCompleted, "tasks completed"],
		[data.taskCompletionRate, "completion rate"],
		[data.tasksAbandoned, "still waiting"],
	];
	for (const [num, label] of items) {
		const cell = createDiv({ cls: "ow-hero" });
		cell.appendChild(heroNum(num));
		cell.appendChild(createDiv({ cls: "ow-hero-label", text: label }));
		grid.appendChild(cell);
	}
	card.appendChild(grid);
	return { id: "tasks", title: `wrapped-${year}-tasks`, element: card };
}

function archetypeZettel(data: WrappedData, accent: string, year: number): WrappedCard {
	const card = createDiv({ cls: "ow-card" });
	const titleEl = createDiv({ cls: "ow-card-title", text: "YOUR WEB OF IDEAS" });
	setAccent(titleEl, accent);
	card.appendChild(titleEl);

	const grid = createDiv({ cls: "ow-rhythm-grid" });
	const cells: [string, string][] = [
		[String(data.linkDensity), "links per note"],
		[`${data.notesWithLinksPct}%`, "notes with links"],
		[`${data.orphanStats.pct}%`, "orphan notes"],
	];
	for (const [num, label] of cells) {
		const cell = createDiv({ cls: "ow-rythm-cell" });
		cell.appendChild(createDiv({ cls: "ow-rhythm-num", text: num }));
		cell.appendChild(createDiv({ cls: "ow-rhythm-label", text: label }));
		grid.appendChild(cell);
	}
	card.appendChild(grid);

	const listLabel = createDiv({ cls: "ow-list-label", text: "Your hubs (most outgoing links)" });
	card.appendChild(listLabel);
	card.appendChild(noteList(data.hubNotes, "links out"));
	return { id: "zettel", title: `wrapped-${year}-zettelkasten`, element: card };
}

function archetypeCollector(data: WrappedData, accent: string, year: number): WrappedCard {
	const card = createDiv({ cls: "ow-card" });
	const titleEl = createDiv({ cls: "ow-card-title", text: "YOUR COLLECTION" });
	setAccent(titleEl, accent);
	card.appendChild(titleEl);

	const grid = createDiv({ cls: "ow-hero-grid" });
	const items: [string, string][] = [
		[formatNumber(data.totalNotesCreatedYear), "notes gathered"],
		[`${data.orphanStats.pct}%`, "orphans"],
		[formatNumber(data.wordsPerNoteYear), "words per note"],
	];
	for (const [num, label] of items) {
		const cell = createDiv({ cls: "ow-hero" });
		cell.appendChild(createDiv({ cls: "ow-hero-num", text: num }));
		cell.appendChild(createDiv({ cls: "ow-hero-label", text: label }));
		grid.appendChild(cell);
	}
	card.appendChild(grid);
	card.appendChild(createDiv({ cls: "ow-note", text: "Quantity is its own kind of knowledge." }));
	return { id: "collector", title: `wrapped-${year}-collector`, element: card };
}
